---
experiment:
  data_dir:  
  dataset: 'FGVCAircraft'
model_params:
  model_base: meta-llama/Llama-2-7b-chat-hf
training:
  eval_val_every: 1
  load: 
  max_epochs: 20
  batch_size: 4
  test_batch_size: 16
  test_set: test
  topk: 1
  workers: 8